os: linux
sudo: required
dist: xenial
compiler: gcc
language: python
python:
  - "2.7"
  
script:
  - sudo apt-get install -y sshpass gettext
  - mkdir subproj
  - git clone https://github.com/sk1project/build-utils subproj/build-utils
  - ln -s subproj/build-utils/src/utils utils
  - git clone https://github.com/sk1project/uniconvertor subproj/uniconvertor
  - ln -s ../subproj/uniconvertor/src/uc2 src/uc2
  - git clone https://github.com/sk1project/wal subproj/wal
  - ln -s ../subproj/wal/src/wal src/wal
  - python setup.py bdist_deb
