os: linux
sudo: required
dist: xenial
compiler: gcc
language: python
python:
  - "2.7"
  
script:
  - sudo apt-get install -y sshpass gettext python-cairo-dev libpango1.0-dev
  - mkdir subproj
  - git clone https://github.com/sk1project/build-utils subproj/build-utils
  - ln -s subproj/build-utils/src/utils utils
  - git clone https://github.com/sk1project/uniconvertor subproj/uniconvertor
  - ln -s ../subproj/uniconvertor/src/uc2 src/uc2
  - git clone https://github.com/sk1project/wal subproj/wal
  - ln -s ../subproj/wal/src/wal src/wal
  - python setup.py bdist_deb
  - ( mkdir appdir ; cd appdir/ ; dpkg-deb -x $(find .. -name 'python-sk1-*.deb') . )
  # Bundle Python
  - cd appdir/
  - apt-get download libpython2.7-stdlib python2.7 python2.7-minimal libpython2.7-minimal
  - find *.deb -exec dpkg-deb -x {} . \;
  - rm *deb
  - cd ..
  - wget -c -nv "https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64" -O ./appdir/AppRun ; chmod +x ./appdir/AppRun
  - cp appdir/usr/lib/sk1-wx-*/sk1/share/icons/generic/sk1-icon-64x64.png appdir/
  - cp appdir/usr/share/applications/sk1.desktop appdir/
  - find appdir/
  - wget -c -nv "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
  - chmod a+x appimagetool-x86_64.AppImage
  - ./appimagetool-x86_64.AppImage appdir/

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh APPNAME*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
